[project]
name = "aid-scene-classification"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.141.1",
    "ipykernel>=7.3.0",
    "jupyter>=1.1.1",
    "matplotlib>=3.11.1",
    "numpy>=2.4.6",
    "pandas>=3.0.5",
    "pillow>=12.3.0",
    "python-multipart>=0.0.32",
    "scikit-learn>=1.9.0",
    "tensorflow>=2.21.0",
    "uvicorn>=0.52.1",
]
